import sys
from pathlib import Path

FONT_CHAR_BYTE_SIZE = 1 + 4 * 10
FONT_RANGE = (0x20, 0x7E)




class DrawException(Exception):
    pass


def bit_aligned8(n):
    return n+7-(n-1)%8


def process_drawing_uncompressed(drawing, char, n_cols=10, n_pages=4, indent=4):
    cols = []
    lc = 0
    kern = 0

    indent = " " * 4

    if drawing is not None:
        print(f"generating from {drawing.name}")

        bits = []
        for l in drawing.read_text().splitlines():
            if not l:
                continue
            page = (lc - lc % 8) // 8
            if page >= n_pages:
                print(f"line #{lc} % 8 >= n_pages {n_pages}")
                raise DrawException(f"line #{lc} % 8 >= n_pages {n_pages}")
            line_split = l.strip().split(" ")
            if len(line_split) != n_cols:
                line_split = list(l.strip())
                if len(line_split) != n_cols:
                    raise DrawException(
                        f"line #{lc} does not contain {n_cols} columns, it contains {len(line_split)}"
                    )
            line_bits = [ord(x) - ord("0") for x in line_split]
            bits.append(line_bits)

            lc += 1

        for lc, line_bits in enumerate(bits):
            page = (lc - lc % 8) // 8
            biti = lc % 8
            for i, bit in enumerate(line_bits):
                if bit == 1:
                    kern = max(kern, i)
                if len(cols) < i + 1:
                    cols.append([0] * n_pages)
                cols[i][page] |= bit << biti

        kern = n_cols - kern - 1

        if char == ord(" "):
            kern = 0

    out = f"{indent * 1}{{\n{indent * 2}.kern = {kern},\n{indent * 2}.data = {{"
    out += f",  //\n{indent * 4} ".join(
        [", ".join([f"0x{byte:02X}" for byte in col]) for col in cols]
    )
    out += f"}},\n{indent * 1}}},"
    return out



def process_drawing_compressed(drawing, char, n_cols=10, n_pages=4, indent=4):
    from encoder import encode, to_bitstring

    if drawing is not None:
        out = ""
        bits = [
            int(x)
            for x in list(
                "".join(
                    [x.strip() for x in drawing.read_text().splitlines() if x.strip()]
                )
            )
        ]

        encodings = encode(bits, verbose=False)
        enc_bits = encodings[0].as_bits()
        original_length = len(bits)
        print(f"{drawing}")
        
        print(f"bit shrink {original_length}->{len(enc_bits)}")
        print(encodings[0].as_bitstring(spacer=" "))

        pad_bits = 0
        if len(enc_bits) % 8 != 0:
            pad_bits = 8 - len(enc_bits) % 8
        if pad_bits > 0:
            enc_bits.append(1)
            enc_bits += [0] * (pad_bits - 1)
        print(f"padding last byte with {pad_bits} bits: {to_bitstring(enc_bits[-pad_bits:])}")

        enc_bytes = []
        for j in range(len(enc_bits) // 8):
            byte = 0
            for i in range(8):
                byte |= enc_bits[j * 8 + i] << (7 - i)
            print(f"{byte:08b}")
            enc_bytes.append(byte)
        out += f"0x{len(enc_bytes):02X}, "
        for byte in enc_bytes:
            out += f"0x{byte:02X}, "
        return out, len(enc_bytes), original_length.bit_length(), original_length
    return "0x00, ", 1, 0, 0


def generate(font_dir, chars_out_dir):
    char_files = list(font_dir.glob("./char_*_*"))
    print(
        f"found {len(char_files)} chars. missing {(0x7E - 0x20) - len(char_files)} for full alphabet"
    )
    char_files_D = {}

    for char_file in char_files:
        _, _, char_code = char_file.stem.split("_")
        try:
            c = int(char_code, 16)
        except:
            print(f"{char_file}: can not convert '{char_code}' to hex")
            return 1
        if c < FONT_RANGE[0] or c > FONT_RANGE[1]:
            print(f"{char_file}: {char_code} is not in range [20, 7E].")
            return 1
        if c in char_files_D:
            print(
                f"found duplicate of {char_code}:\n  {char_file}\n  {char_files_D[c]}."
            )
            return 1
        char_files_D[c] = char_file

    for c in range(*FONT_RANGE):
        if c not in char_files_D:
            char_files_D[c] = None

    CHARS_C = "/*  THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.  */\n"
    CHARS_C += '#include "chars.h"\n'

    # uncompressed
    CHARS_C += "#ifdef FONT_UNCOMPRESSED\n"
    CHARS_C += "const FontChar PROGMEM font[] = {\n"
    CHARS_C += "\n".join(
        [process_drawing_uncompressed(char_files_D[c], c) for c in range(*FONT_RANGE)]
    )
    CHARS_C += "\n};\n"

    # compression
    CHARS_C += "#else\n"
    CHARS_C += "#ifdef FONT_COMPRESSED\n"
    len_message = 0
    bitlen_message = 0
    bitlen_pattern_length = 0
    _out = ""
    enc_font_mem_size = 0
    for c in range(*FONT_RANGE):
        s, num_enc_bytes, _bitlen_message, _len_message = process_drawing_compressed(
            char_files_D[c], c
        )
        bitlen_message = max(_bitlen_message, bitlen_message)
        len_message = max(_len_message, len_message)
        bitlen_pattern_length = bitlen_message - 1
        _out += f"{s}\n"
        enc_font_mem_size += num_enc_bytes


    CHARS_C += "const uint8_t PROGMEM font[] = {\n"
    CHARS_C += _out
    CHARS_C += "\n};\n"
    CHARS_C += "#endif\n"
    CHARS_C += "#endif\n"

    CHARS_H = f"""/*  THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.  */
#pragma once
#include "fontchar.h"
#include <avr/pgmspace.h>
#ifdef FONT_UNCOMPRESSED
extern const FontChar PROGMEM font[];
#else
#ifdef FONT_COMPRESSED
#define FONT_COMP_BITLEN_ORIGINAL (uint8_t){bitlen_message}
#define FONT_COMP_BITLEN_PATTERN_LENGTH (uint8_t){bitlen_pattern_length}
#define FONT_COMP_ENC_MAX_BYTES (uint8_t){bit_aligned8(1 + bitlen_message + len_message)//8}
typedef uint{bit_aligned8(bitlen_message)}_t uint_BITLEN_LITERAL_LENGTH_t;
typedef uint{bit_aligned8(bitlen_pattern_length)}_t uint_BITLEN_PATTERN_LENTGTH_t;
extern const uint8_t PROGMEM font[];
#endif
#endif
"""

    written_text = (chars_out_dir / "chars.h").write_text(CHARS_H)
    written_text += (chars_out_dir / "chars.c").write_text(CHARS_C)

    print(f"written {written_text} bytes to {chars_out_dir}/chars.h and {chars_out_dir}/chars.c")
    print(f"font has {FONT_RANGE[1] - FONT_RANGE[0]} chars")
    print(
        f"uncompressed font memory size: {FONT_CHAR_BYTE_SIZE * (FONT_RANGE[1] - FONT_RANGE[0])} bytes"
    )
    print(f"compressed font memory size: {enc_font_mem_size} bytes")


def cli():
    usage = f"""Usage: 
python path/to/make_font.py path/to/font path/to/out
    path/to/font should list char files of this format:
        char_{{identifier of your choice}}_{{charactor code in hex}}
        missing chars for range [{FONT_RANGE[0]}, {FONT_RANGE[1]}] will not be generated
    path/to/out is the output directory where 'chars.c' and 'chars.h' will be placed."""
    args = sys.argv[1:]
    if len(args) <= 1:
        print(usage)
        return 1
    try:
        font_dir = Path(args[0])
    except:
        print(f"{args[0]} is not a path.")
        return 1
    try:
        chars_out_dir = Path(args[1])
    except:
        print(f"{args[1]} is not a path.")
        return 1
    if not font_dir.exists():
        print(f"path/to/font: dir '{font_dir}' does not exist.")
        return 1
    if not chars_out_dir.exists():
        print(f"path/to/font: dir '{chars_out_dir}' does not exist.")
        return 1
    (chars_out_dir / "chars.c").touch(exist_ok=True)
    (chars_out_dir / "chars.h").touch(exist_ok=True)
    return font_dir, chars_out_dir


if __name__ == "__main__":
    ret = cli()
    if ret == 1:
        sys.exit(1)
    else:
        generate(*ret)
